### ISSUE TITLE
[FEATURE] Create Logo for the app

### ISSUE THREAD

**Issue by WilChrist** [BuildForSDG/Team-220-Frontend#8]
**Is your feature request related to a problem? Please describe.**
For now our app just use default angular logo.

**Describe the solution you'd like**
Create our Own Logo, then adapt it to the differents size found in the src/assets/icons/ and replace them. Don't forget to also create a corresponding favicon and remplace the one in the root of the project.

**Comment by NelGab** [comment]
done
